-- SUPERSEDED — do not apply.
--
-- This file lived in a non-standard `migrations/new/` subfolder, which the Supabase CLI
-- never picks up, so it was never actually applied anywhere. It has been corrected
-- (missing `notifications_enabled` column, missing UNIQUE(user_id) constraint needed by
-- the app's upsert) and moved into the real migration sequence at:
--   supabase/migrations/20260625174100_create_user_preferences.sql
--
-- This file is kept only so the history isn't silently deleted. It is safe to remove
-- this `migrations/new/` folder entirely once you've confirmed the migration above has
-- been applied to your live database.
