/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ApexRouteImport } from './routes/_apex'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as DivisionsIndexRouteImport } from './routes/divisions.index'
import { Route as PortalSignupRouteImport } from './routes/portal.signup'
import { Route as PortalLoginRouteImport } from './routes/portal.login'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as DivisionsTechnologyRouteImport } from './routes/divisions.technology'
import { Route as DivisionsRealEstateRouteImport } from './routes/divisions.real-estate'
import { Route as DivisionsLogisticsRouteImport } from './routes/divisions.logistics'
import { Route as DivisionsIntelligenceRouteImport } from './routes/divisions.intelligence'
import { Route as DivisionsInnovationLabRouteImport } from './routes/divisions.innovation-lab'
import { Route as DivisionsAgritechRouteImport } from './routes/divisions.agritech'
import { Route as ApexPortalSettingsRouteImport } from './routes/_apex.portal.settings'
import { Route as ApexPortalDashboardRouteImport } from './routes/_apex.portal.dashboard'
import { Route as ApexPortalAuditRouteImport } from './routes/_apex.portal.audit'
import { Route as ApexPortalProjectsIndexRouteImport } from './routes/_apex.portal.projects.index'
import { Route as ApexPortalProjectsIdRouteImport } from './routes/_apex.portal.projects.$id'
import { Route as ApexPortalDivisionsTechnologyRouteImport } from './routes/_apex.portal.divisions.technology'
import { Route as ApexPortalDivisionsAgritechRouteImport } from './routes/_apex.portal.divisions.agritech'
import { Route as ApexPortalDivisionsSlugRouteImport } from './routes/_apex.portal.divisions.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApexRoute = ApexRouteImport.update({
  id: '/_apex',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const DivisionsIndexRoute = DivisionsIndexRouteImport.update({
  id: '/divisions/',
  path: '/divisions/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalSignupRoute = PortalSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PortalRoute,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InsightsRoute,
} as any)
const DivisionsTechnologyRoute = DivisionsTechnologyRouteImport.update({
  id: '/divisions/technology',
  path: '/divisions/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const DivisionsRealEstateRoute = DivisionsRealEstateRouteImport.update({
  id: '/divisions/real-estate',
  path: '/divisions/real-estate',
  getParentRoute: () => rootRouteImport,
} as any)
const DivisionsLogisticsRoute = DivisionsLogisticsRouteImport.update({
  id: '/divisions/logistics',
  path: '/divisions/logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const DivisionsIntelligenceRoute = DivisionsIntelligenceRouteImport.update({
  id: '/divisions/intelligence',
  path: '/divisions/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const DivisionsInnovationLabRoute = DivisionsInnovationLabRouteImport.update({
  id: '/divisions/innovation-lab',
  path: '/divisions/innovation-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const DivisionsAgritechRoute = DivisionsAgritechRouteImport.update({
  id: '/divisions/agritech',
  path: '/divisions/agritech',
  getParentRoute: () => rootRouteImport,
} as any)
const ApexPortalSettingsRoute = ApexPortalSettingsRouteImport.update({
  id: '/portal/settings',
  path: '/portal/settings',
  getParentRoute: () => ApexRoute,
} as any)
const ApexPortalDashboardRoute = ApexPortalDashboardRouteImport.update({
  id: '/portal/dashboard',
  path: '/portal/dashboard',
  getParentRoute: () => ApexRoute,
} as any)
const ApexPortalAuditRoute = ApexPortalAuditRouteImport.update({
  id: '/portal/audit',
  path: '/portal/audit',
  getParentRoute: () => ApexRoute,
} as any)
const ApexPortalProjectsIndexRoute = ApexPortalProjectsIndexRouteImport.update({
  id: '/portal/projects/',
  path: '/portal/projects/',
  getParentRoute: () => ApexRoute,
} as any)
const ApexPortalProjectsIdRoute = ApexPortalProjectsIdRouteImport.update({
  id: '/portal/projects/$id',
  path: '/portal/projects/$id',
  getParentRoute: () => ApexRoute,
} as any)
const ApexPortalDivisionsTechnologyRoute =
  ApexPortalDivisionsTechnologyRouteImport.update({
    id: '/portal/divisions/technology',
    path: '/portal/divisions/technology',
    getParentRoute: () => ApexRoute,
  } as any)
const ApexPortalDivisionsAgritechRoute =
  ApexPortalDivisionsAgritechRouteImport.update({
    id: '/portal/divisions/agritech',
    path: '/portal/divisions/agritech',
    getParentRoute: () => ApexRoute,
  } as any)
const ApexPortalDivisionsSlugRoute = ApexPortalDivisionsSlugRouteImport.update({
  id: '/portal/divisions/$slug',
  path: '/portal/divisions/$slug',
  getParentRoute: () => ApexRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/divisions/agritech': typeof DivisionsAgritechRoute
  '/divisions/innovation-lab': typeof DivisionsInnovationLabRoute
  '/divisions/intelligence': typeof DivisionsIntelligenceRoute
  '/divisions/logistics': typeof DivisionsLogisticsRoute
  '/divisions/real-estate': typeof DivisionsRealEstateRoute
  '/divisions/technology': typeof DivisionsTechnologyRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/signup': typeof PortalSignupRoute
  '/divisions/': typeof DivisionsIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/audit': typeof ApexPortalAuditRoute
  '/portal/dashboard': typeof ApexPortalDashboardRoute
  '/portal/settings': typeof ApexPortalSettingsRoute
  '/portal/divisions/$slug': typeof ApexPortalDivisionsSlugRoute
  '/portal/divisions/agritech': typeof ApexPortalDivisionsAgritechRoute
  '/portal/divisions/technology': typeof ApexPortalDivisionsTechnologyRoute
  '/portal/projects/$id': typeof ApexPortalProjectsIdRoute
  '/portal/projects/': typeof ApexPortalProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRouteWithChildren
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/divisions/agritech': typeof DivisionsAgritechRoute
  '/divisions/innovation-lab': typeof DivisionsInnovationLabRoute
  '/divisions/intelligence': typeof DivisionsIntelligenceRoute
  '/divisions/logistics': typeof DivisionsLogisticsRoute
  '/divisions/real-estate': typeof DivisionsRealEstateRoute
  '/divisions/technology': typeof DivisionsTechnologyRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/signup': typeof PortalSignupRoute
  '/divisions': typeof DivisionsIndexRoute
  '/portal': typeof PortalIndexRoute
  '/portal/audit': typeof ApexPortalAuditRoute
  '/portal/dashboard': typeof ApexPortalDashboardRoute
  '/portal/settings': typeof ApexPortalSettingsRoute
  '/portal/divisions/$slug': typeof ApexPortalDivisionsSlugRoute
  '/portal/divisions/agritech': typeof ApexPortalDivisionsAgritechRoute
  '/portal/divisions/technology': typeof ApexPortalDivisionsTechnologyRoute
  '/portal/projects/$id': typeof ApexPortalProjectsIdRoute
  '/portal/projects': typeof ApexPortalProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_apex': typeof ApexRouteWithChildren
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/divisions/agritech': typeof DivisionsAgritechRoute
  '/divisions/innovation-lab': typeof DivisionsInnovationLabRoute
  '/divisions/intelligence': typeof DivisionsIntelligenceRoute
  '/divisions/logistics': typeof DivisionsLogisticsRoute
  '/divisions/real-estate': typeof DivisionsRealEstateRoute
  '/divisions/technology': typeof DivisionsTechnologyRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/signup': typeof PortalSignupRoute
  '/divisions/': typeof DivisionsIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/_apex/portal/audit': typeof ApexPortalAuditRoute
  '/_apex/portal/dashboard': typeof ApexPortalDashboardRoute
  '/_apex/portal/settings': typeof ApexPortalSettingsRoute
  '/_apex/portal/divisions/$slug': typeof ApexPortalDivisionsSlugRoute
  '/_apex/portal/divisions/agritech': typeof ApexPortalDivisionsAgritechRoute
  '/_apex/portal/divisions/technology': typeof ApexPortalDivisionsTechnologyRoute
  '/_apex/portal/projects/$id': typeof ApexPortalProjectsIdRoute
  '/_apex/portal/projects/': typeof ApexPortalProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/insights'
    | '/portal'
    | '/services'
    | '/sitemap.xml'
    | '/divisions/agritech'
    | '/divisions/innovation-lab'
    | '/divisions/intelligence'
    | '/divisions/logistics'
    | '/divisions/real-estate'
    | '/divisions/technology'
    | '/insights/$slug'
    | '/portal/login'
    | '/portal/signup'
    | '/divisions/'
    | '/portal/'
    | '/portal/audit'
    | '/portal/dashboard'
    | '/portal/settings'
    | '/portal/divisions/$slug'
    | '/portal/divisions/agritech'
    | '/portal/divisions/technology'
    | '/portal/projects/$id'
    | '/portal/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/insights'
    | '/services'
    | '/sitemap.xml'
    | '/divisions/agritech'
    | '/divisions/innovation-lab'
    | '/divisions/intelligence'
    | '/divisions/logistics'
    | '/divisions/real-estate'
    | '/divisions/technology'
    | '/insights/$slug'
    | '/portal/login'
    | '/portal/signup'
    | '/divisions'
    | '/portal'
    | '/portal/audit'
    | '/portal/dashboard'
    | '/portal/settings'
    | '/portal/divisions/$slug'
    | '/portal/divisions/agritech'
    | '/portal/divisions/technology'
    | '/portal/projects/$id'
    | '/portal/projects'
  id:
    | '__root__'
    | '/'
    | '/_apex'
    | '/about'
    | '/careers'
    | '/contact'
    | '/insights'
    | '/portal'
    | '/services'
    | '/sitemap.xml'
    | '/divisions/agritech'
    | '/divisions/innovation-lab'
    | '/divisions/intelligence'
    | '/divisions/logistics'
    | '/divisions/real-estate'
    | '/divisions/technology'
    | '/insights/$slug'
    | '/portal/login'
    | '/portal/signup'
    | '/divisions/'
    | '/portal/'
    | '/_apex/portal/audit'
    | '/_apex/portal/dashboard'
    | '/_apex/portal/settings'
    | '/_apex/portal/divisions/$slug'
    | '/_apex/portal/divisions/agritech'
    | '/_apex/portal/divisions/technology'
    | '/_apex/portal/projects/$id'
    | '/_apex/portal/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApexRoute: typeof ApexRouteWithChildren
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  InsightsRoute: typeof InsightsRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DivisionsAgritechRoute: typeof DivisionsAgritechRoute
  DivisionsInnovationLabRoute: typeof DivisionsInnovationLabRoute
  DivisionsIntelligenceRoute: typeof DivisionsIntelligenceRoute
  DivisionsLogisticsRoute: typeof DivisionsLogisticsRoute
  DivisionsRealEstateRoute: typeof DivisionsRealEstateRoute
  DivisionsTechnologyRoute: typeof DivisionsTechnologyRoute
  DivisionsIndexRoute: typeof DivisionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_apex': {
      id: '/_apex'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ApexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/divisions/': {
      id: '/divisions/'
      path: '/divisions'
      fullPath: '/divisions/'
      preLoaderRoute: typeof DivisionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/signup': {
      id: '/portal/signup'
      path: '/signup'
      fullPath: '/portal/signup'
      preLoaderRoute: typeof PortalSignupRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof PortalRoute
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/divisions/technology': {
      id: '/divisions/technology'
      path: '/divisions/technology'
      fullPath: '/divisions/technology'
      preLoaderRoute: typeof DivisionsTechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/divisions/real-estate': {
      id: '/divisions/real-estate'
      path: '/divisions/real-estate'
      fullPath: '/divisions/real-estate'
      preLoaderRoute: typeof DivisionsRealEstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/divisions/logistics': {
      id: '/divisions/logistics'
      path: '/divisions/logistics'
      fullPath: '/divisions/logistics'
      preLoaderRoute: typeof DivisionsLogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/divisions/intelligence': {
      id: '/divisions/intelligence'
      path: '/divisions/intelligence'
      fullPath: '/divisions/intelligence'
      preLoaderRoute: typeof DivisionsIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/divisions/innovation-lab': {
      id: '/divisions/innovation-lab'
      path: '/divisions/innovation-lab'
      fullPath: '/divisions/innovation-lab'
      preLoaderRoute: typeof DivisionsInnovationLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/divisions/agritech': {
      id: '/divisions/agritech'
      path: '/divisions/agritech'
      fullPath: '/divisions/agritech'
      preLoaderRoute: typeof DivisionsAgritechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_apex/portal/settings': {
      id: '/_apex/portal/settings'
      path: '/portal/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof ApexPortalSettingsRouteImport
      parentRoute: typeof ApexRoute
    }
    '/_apex/portal/dashboard': {
      id: '/_apex/portal/dashboard'
      path: '/portal/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof ApexPortalDashboardRouteImport
      parentRoute: typeof ApexRoute
    }
    '/_apex/portal/audit': {
      id: '/_apex/portal/audit'
      path: '/portal/audit'
      fullPath: '/portal/audit'
      preLoaderRoute: typeof ApexPortalAuditRouteImport
      parentRoute: typeof ApexRoute
    }
    '/_apex/portal/projects/': {
      id: '/_apex/portal/projects/'
      path: '/portal/projects'
      fullPath: '/portal/projects/'
      preLoaderRoute: typeof ApexPortalProjectsIndexRouteImport
      parentRoute: typeof ApexRoute
    }
    '/_apex/portal/projects/$id': {
      id: '/_apex/portal/projects/$id'
      path: '/portal/projects/$id'
      fullPath: '/portal/projects/$id'
      preLoaderRoute: typeof ApexPortalProjectsIdRouteImport
      parentRoute: typeof ApexRoute
    }
    '/_apex/portal/divisions/technology': {
      id: '/_apex/portal/divisions/technology'
      path: '/portal/divisions/technology'
      fullPath: '/portal/divisions/technology'
      preLoaderRoute: typeof ApexPortalDivisionsTechnologyRouteImport
      parentRoute: typeof ApexRoute
    }
    '/_apex/portal/divisions/agritech': {
      id: '/_apex/portal/divisions/agritech'
      path: '/portal/divisions/agritech'
      fullPath: '/portal/divisions/agritech'
      preLoaderRoute: typeof ApexPortalDivisionsAgritechRouteImport
      parentRoute: typeof ApexRoute
    }
    '/_apex/portal/divisions/$slug': {
      id: '/_apex/portal/divisions/$slug'
      path: '/portal/divisions/$slug'
      fullPath: '/portal/divisions/$slug'
      preLoaderRoute: typeof ApexPortalDivisionsSlugRouteImport
      parentRoute: typeof ApexRoute
    }
  }
}

interface ApexRouteChildren {
  ApexPortalAuditRoute: typeof ApexPortalAuditRoute
  ApexPortalDashboardRoute: typeof ApexPortalDashboardRoute
  ApexPortalSettingsRoute: typeof ApexPortalSettingsRoute
  ApexPortalDivisionsSlugRoute: typeof ApexPortalDivisionsSlugRoute
  ApexPortalDivisionsAgritechRoute: typeof ApexPortalDivisionsAgritechRoute
  ApexPortalDivisionsTechnologyRoute: typeof ApexPortalDivisionsTechnologyRoute
  ApexPortalProjectsIdRoute: typeof ApexPortalProjectsIdRoute
  ApexPortalProjectsIndexRoute: typeof ApexPortalProjectsIndexRoute
}

const ApexRouteChildren: ApexRouteChildren = {
  ApexPortalAuditRoute: ApexPortalAuditRoute,
  ApexPortalDashboardRoute: ApexPortalDashboardRoute,
  ApexPortalSettingsRoute: ApexPortalSettingsRoute,
  ApexPortalDivisionsSlugRoute: ApexPortalDivisionsSlugRoute,
  ApexPortalDivisionsAgritechRoute: ApexPortalDivisionsAgritechRoute,
  ApexPortalDivisionsTechnologyRoute: ApexPortalDivisionsTechnologyRoute,
  ApexPortalProjectsIdRoute: ApexPortalProjectsIdRoute,
  ApexPortalProjectsIndexRoute: ApexPortalProjectsIndexRoute,
}

const ApexRouteWithChildren = ApexRoute._addFileChildren(ApexRouteChildren)

interface InsightsRouteChildren {
  InsightsSlugRoute: typeof InsightsSlugRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsSlugRoute: InsightsSlugRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

interface PortalRouteChildren {
  PortalLoginRoute: typeof PortalLoginRoute
  PortalSignupRoute: typeof PortalSignupRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalLoginRoute: PortalLoginRoute,
  PortalSignupRoute: PortalSignupRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApexRoute: ApexRouteWithChildren,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  InsightsRoute: InsightsRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DivisionsAgritechRoute: DivisionsAgritechRoute,
  DivisionsInnovationLabRoute: DivisionsInnovationLabRoute,
  DivisionsIntelligenceRoute: DivisionsIntelligenceRoute,
  DivisionsLogisticsRoute: DivisionsLogisticsRoute,
  DivisionsRealEstateRoute: DivisionsRealEstateRoute,
  DivisionsTechnologyRoute: DivisionsTechnologyRoute,
  DivisionsIndexRoute: DivisionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
