-- Innovation Lab deep-build: a prototype image gallery (screenshots column already
-- existed but had no storage bucket or upload path), an AI-generated MVP checklist
-- per idea, a demo day scheduler, and an experiment log that can link straight to a
-- UIG Intelligence model.

-- ===== MVP checklist (generated by AI, then checkable like a normal to-do list) =====
CREATE TABLE public.mvp_checklist_items (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  idea_id uuid NOT NULL REFERENCES public.ideas(id) ON DELETE CASCADE,
  task text NOT NULL,
  done boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ===== Demo day scheduler =====
CREATE TABLE public.demo_days (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  title text NOT NULL,
  event_date date NOT NULL,
  status text NOT NULL DEFAULT 'upcoming' CHECK (status IN ('upcoming', 'completed', 'cancelled')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.demo_day_slots (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  demo_day_id uuid NOT NULL REFERENCES public.demo_days(id) ON DELETE CASCADE,
  prototype_id uuid NOT NULL REFERENCES public.prototypes(id) ON DELETE CASCADE,
  slot_time text,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (demo_day_id, prototype_id)
);

-- ===== Experiment log — optionally tied to a real UIG Intelligence model =====
CREATE TABLE public.experiments (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  idea_id uuid REFERENCES public.ideas(id) ON DELETE SET NULL,
  prototype_id uuid REFERENCES public.prototypes(id) ON DELETE SET NULL,
  model_id uuid REFERENCES public.models(id) ON DELETE SET NULL,
  hypothesis text NOT NULL,
  result text,
  status text NOT NULL DEFAULT 'planned' CHECK (status IN ('planned', 'running', 'concluded')),
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ===== Grants =====
GRANT SELECT, INSERT, UPDATE, DELETE ON public.mvp_checklist_items TO authenticated;
GRANT ALL ON public.mvp_checklist_items TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.demo_days TO authenticated;
GRANT ALL ON public.demo_days TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.demo_day_slots TO authenticated;
GRANT ALL ON public.demo_day_slots TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.experiments TO authenticated;
GRANT ALL ON public.experiments TO service_role;

-- ===== RLS — mirrors the existing blanket auth_* policy style already used for
-- ideas/prototypes/partners in this division (see 20260615000000_*.sql) rather than
-- the has_division_access() pattern used by other divisions, for consistency with
-- how this division's own tables were already set up. =====
ALTER TABLE public.mvp_checklist_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.demo_days ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.demo_day_slots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.experiments ENABLE ROW LEVEL SECURITY;

CREATE POLICY auth_mvp_checklist_items ON public.mvp_checklist_items FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY auth_demo_days ON public.demo_days FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY auth_demo_day_slots ON public.demo_day_slots FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY auth_experiments ON public.experiments FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ===== Storage bucket for prototype screenshots (public read) =====
INSERT INTO storage.buckets (id, name, public) VALUES ('prototype-images', 'prototype-images', true)
  ON CONFLICT (id) DO NOTHING;

CREATE POLICY "anyone reads prototype images" ON storage.objects
  FOR SELECT TO public
  USING (bucket_id = 'prototype-images');

CREATE POLICY "authenticated upload prototype images" ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'prototype-images');

CREATE POLICY "authenticated delete prototype images" ON storage.objects
  FOR DELETE TO authenticated
  USING (bucket_id = 'prototype-images');
